### ISSUE TITLE
this three dataset is too huge, would you please share the hdf5 dataset you get after the modeling training???Thanks

### ISSUE THREAD

**Issue by Bigwode** [StanfordVL/ReferringRelationships#1]
this three dataset is too huge, would you please share the hdf5 dataset you get after the modeling training???Thanks

**Comment by AlanGCheng** [comment]
Can't agree more !

**Comment by zhuyanshuo** [comment]
please！thanks very much！

**Comment by ranjaykrishna** [comment]
Sorry you will have to download them and run our script to convert them into hdf5.

You can visualize the test results by using one of our various ipython notebooks in the repository.

**Comment by jageshmaharjan** [comment]
The created dataset is massive

```
dsdev@dsdev:/mnt/data/dataset-visualgenome$ du -h --max-depth=1
40G	./train
4.4G	./val
4.9G	./test
49G	.

```
