### ISSUE TITLE
Could not obtain images.hdf5

### ISSUE THREAD

**Issue by handsomefengfeng** [StanfordVL/ReferringRelationships#11]
I've completely finished the experiment on VRD dataset.
After the conversion, I obtained images.hdf5 and dataset.hdf5.

But when converting the CLEVR dataset into *.hdf5 pattern,
I could only obtain dataset.hdf5 without images.hdf5.

Besides, I found there's create_small_clevr_dataset.sh and it works.
Using the create_small_clevr_dataset.sh, I could obtain both images.hdf5 and datset.hdf5.
With the data converted by create_small_clevr_dataset.sh, would the result be affected?

Could please give me some suggestions? 
Thanks!

**Comment by ranjaykrishna** [comment]
Just updated the script by adding --save-images option. It should now be saving the images too. Check out the commit here: https://github.com/StanfordVL/ReferringRelationships/commit/61e04c1ccad6a7f7dcbc07562ef68546ba4063cf
