### ISSUE TITLE
Bug in model definition when training Visual Genome

### ISSUE THREAD

**Issue by JieChen91** [StanfordVL/ReferringRelationships#2]
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    model = relationships_model.build_model()
  File "/home/jiechen/code/ReferringRelationships/models.py", line 75, in build_model
    return self.build_ssas()
  File "/home/jiechen/code/ReferringRelationships/models.py", line 154, in build_ssas
    subject_att = Concatenate(axis=3)(subject_outputs)
  File "/home/jiechen/anaconda3/envs/rel/lib/python3.6/site-packages/keras/engine/topology.py", line 583, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/home/jiechen/anaconda3/envs/rel/lib/python3.6/site-packages/keras/engine/topology.py", line 2752, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
IndexError: list index out of range

**Comment by JieChen91** [comment]
I use pub to see the size of subject_outputs, they seem the same:
(Pdb) subject_outputs[0]                                                                                                                                      
<tf.Tensor 'lambda_15/mul:0' shape=(?, 14, 14, 1) dtype=float32>
(Pdb) subject_outputs[1]                                                                                                                                      
<tf.Tensor 'lambda_15/mul_1:0' shape=(?, 14, 14, 1) dtype=float32>
(Pdb) subject_outputs[2]                                                                                                                                      
<tf.Tensor 'lambda_15/mul_2:0' shape=(?, 14, 14, 1) dtype=float32>
(Pdb) subject_outputs[3]                                                                                                                                      
<tf.Tensor 'lambda_15/mul_3:0' shape=(?, 14, 14, 1) dtype=float32>

**Comment by dhimanpd** [comment]
@JieChen91 Seems to be a version mismatch issue. Try using following keras and tf version.
```
>>> keras.__version__
'2.1.6'
>>> tf.__version__
'1.6.0'
```

**Comment by handsomefengfeng** [comment]
I met the same problem when I started to train on VRD.
Did you solve the problem by updating you keras to 2.1.6, tensorflow to 1.6.0 ?
My environment:
`h5py==2.7.1
Keras==2.0.6
numpy==1.13.3
olefile==0.44
Pillow==4.3.0
protobuf==3.4.0
PyYAML==3.12
scipy==0.19.1
six==1.11.0
tensorflow-gpu==1.1.0
Theano==0.9.0
Werkzeug==0.12.2
`
