### ISSUE TITLE
About the VRD dataset

### ISSUE THREAD

**Issue by Luomin1993** [StanfordVL/ReferringRelationships#3]
Where can I download the VRD dataset's images???
I notice that there are only annotations for the VRD dataset where I can download.

**Comment by ranjaykrishna** [comment]
Here you go: http://imagenet.stanford.edu/internal/jcjohns/scene_graphs/sg_dataset.zip

**Comment by brleandro** [comment]
> Here you go: http://imagenet.stanford.edu/internal/jcjohns/scene_graphs/sg_dataset.zip

This link is broken. Does anyone know where we can find the images of VRD dataset?

**Comment by StarLiu714** [comment]
> > Here you go: http://imagenet.stanford.edu/internal/jcjohns/scene_graphs/sg_dataset.zip
> 
> This link is broken. Does anyone know where we can find the images of VRD dataset?

same. it is not available and still not find any alternative link

**Comment by hanruijiang** [comment]
> Here you go: http://imagenet.stanford.edu/internal/jcjohns/scene_graphs/sg_dataset.zip

hi @ranjaykrishna , the link is broken. do you have a copy and could you please share the link with me ?

thank you.

http://imagenet.stanford.edu/internal/jcjohns/scene_graphs/sg_dataset.zip
