### ISSUE TITLE
typo in pipeline diagram

### ISSUE THREAD

**Issue by youngfly11** [StanfordVL/ReferringRelationships#4]
<img width="944" alt="2018-10-15 14 37 57" src="https://user-images.githubusercontent.com/24568308/46933816-2a621200-d088-11e8-9c7b-7667d71e103a.png">

I think the diagram are wrong. It's easy to know the output of upper branch is object localization results.

**Comment by ranjaykrishna** [comment]
Yup. We plan on updating this soon.
