### ISSUE TITLE
Dimension of image features

### ISSUE THREAD

**Issue by Jaesuny** [StanfordVL/ReferringRelationships#5]
According to the paper, the dimension of image features is 14 × 14 × 512.
But, the dimension of the features used in `train_visualgenome.sh` is 14 × 14 × 1024.

![image](https://user-images.githubusercontent.com/10977800/52455936-fb6f2f00-2b95-11e9-92a8-6faf2b990bd1.png)
The layer of ResNet50 used in `train_visualgenome.sh` is `activation_40`

**Comment by ranjaykrishna** [comment]
Ah you are right. The paper should say 14 x 14 x 1024.
